import time


print("CREDITS!")
time.sleep(2)
print("We hope you enjoyed the game, this is the first game we have made.")
time.sleep(2)
print("Anyway here comes the credits   ")
time.sleep(3)
print("TextTale:")
time.sleep(2)
print("Original idea by: TrazNarf")
time.sleep(2)
print("Owner: TrazNarf")
time.sleep(1)
print("Co-Owner: Baaron1")
time.sleep(2)
print("Lead developer: Baaron1")
time.sleep(2)
print("The real person to thank: Toby Fox")
time.sleep(1)
print("Toby Fox made Undertale which is what we based this game off of")
time.sleep(2)
print("We recommend you play the original Undertale at: https://store.steampowered.com/app/391540/Undertale/")
time.sleep(4)